#!/bin/bash
#created by: Yroll Jay-R Macalino
#initialization-centOS7-forwarding-2018
cgreen="\e[32m"
cred="\e[31m"
cblue="\e[34m"
cyellow="\e[33m"
ccyan="\e[36m"
cmagenta="\e[35m"
cwhite="\e[97m"
cnormal="\e[39m"
location="/home/`whoami`/aom/"
