#created by: Yroll Jay-R Macalino
---
- hosts: 127.0.0.1
  gather_facts: no
  tasks:
  - name: Check that you can connect (GET) to a page and it returns a status 200
    uri:
     url: http://{{ item }}
    with_items:
      - agent68.net
      - agent28.net
      - xdl951.net
      - deli1818.com
      - deli28.com
      - xindeli168.com
      - xindeli789.com
      - deliyifa.com
      - deli13145.com
      - xdl357.net
    ignore_errors: yes
  - name: A record (IPV4 address) lookup
    debug: msg='{{ lookup('dig', '{{ item }}')}}'
    with_items:
      - agent68.net
      - agent28.net
      - xdl951.net
      - deli1818.com
      - deli28.com
      - xindeli168.com
      - xindeli789.com
      - deliyifa.com
      - deli13145.com
      - xdl357.net
    ignore_errors: yes


