#credits to: Paul Cyrus Verzola and Jommel Valdez
#created by: Yroll Jay-R Macalino
---
- hosts: 127.0.0.1
  gather_facts: no

  vars_prompt:
  - name: "pc-settings-password"
    prompt: "Office Settings Password"
    private: yes
  - name: "question1"
    prompt: "############################\nIF HAVING PROBLEM WITH NAMING, ASK JAX/AARON\n############################\nPlease enter the group and type: \nSample: bbet8-nginx, acc-midpay_ftp \n############################\n"
    private: no
  tasks:
  - name: "question2"
    debug:
     msg: 'Server Count number:\nSample: "{{ question1 }}"1, "{{ question1 }}"7 \n############################\n'