---
- hosts: ssr_init
  gather_facts: yes

  roles:
    - p.ssr_init
    - p.ssr_install
  tags: "initialization_ssr"


- hosts: ssr_config
  gather_facts: yes

  roles:
    - p.ssr_config
  tags: "config_ssr"
  become: True

- hosts: ssr_fileconfig
  gather_facts: yes
  roles:
    - p.ssr_fileconfig
  tags: "fileconfig_ssr"
  become: True



- hosts: v2ray_init
  gather_facts: yes
  roles:
    - p.v2ray_install
    - p.v2ray_nginx
  tags: "initialization_v2ray"
  become: True
