---

- hosts: ssr_config

  gather_facts: no

  become: true



  tasks:

    - name: "Restarting"

      service:

        name: v2ray

        state: restarted

      ignore_errors: yes



    - name: "Restarting"

      systemd:

        name: v2ray

        state: restarted

      ignore_errors: yes


