# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-20 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BUSINESS_UNIT',
            fields=[
                ('business_unit', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Business Unit')),
            ],
            options={
                'verbose_name': 'Business Units',
                'verbose_name_plural': 'Business Units',
            },
        ),
    ]
