# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-22 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180422_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool_link',
            name='tool_url',
            field=models.CharField(max_length=255, verbose_name='Tool URL'),
        ),
    ]
