# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-05 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_business_unit_kibana_endpoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business_unit',
            name='kibana_endpoint',
        ),
        migrations.AddField(
            model_name='business_unit',
            name='cpms_platform_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='CPMS Platform ID'),
        ),
        migrations.AddField(
            model_name='business_unit',
            name='es_endpoint',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ES Endpoint'),
        ),
    ]
