# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-20 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180905_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_unit',
            name='domain_status_check',
            field=models.BooleanField(default=False, verbose_name='Domains Status Check'),
        ),
    ]
