# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-24 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_business_unit_domain_status_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool_link',
            name='tool_type',
        ),
        migrations.RemoveField(
            model_name='business_unit',
            name='es_endpoint',
        ),
        migrations.AddField(
            model_name='business_unit',
            name='logstash_api',
            field=models.BooleanField(default=False, verbose_name='Logstash API'),
        ),
        migrations.DeleteModel(
            name='TOOL_LINK',
        ),
        migrations.DeleteModel(
            name='TOOL_TYPE',
        ),
    ]
