---
- name: Configuring ulimit2
  pam_limits:
    domain: '*'
    limit_type: "{{ item.ltype }}"
    limit_item: "{{ item.litem }}"
    value: "{{ item.vlue }}"
  with_items:
    - { ltype: 'soft', litem: 'nofile', vlue: '51200' }
    - { ltype: 'hard', litem: 'nofile', vlue: '65536' }