---
- name: Creating ommgr user                                                       #Creating ommgr user
  user:
    name: '{{ ssr_user }}'
    home: '/home/{{ ssr_user }}'
    createhome: yes
    state: present



- name: Creating directory                                                        #Creating directory
  file:
    path: '/home/{{ ssr_user }}/.ssh'
    owner: '{{ ssr_user }}'
    group: '{{ ssr_user }}'
    state: directory
    mode: 0700