- name: Configuring /etc/pam.d/login (x86_64)
  lineinfile:
    dest: '/etc/pam.d/login'
    line: 'session   required    /lib64/security/pam_limits.so'
    state: present
    insertafter: EOF
  when: 'ansible_architecture == "x86_64"'




- name: Configuring /etc/pam.d/login (i386)
  lineinfile:
    dest: '/etc/pam.d/login'
    line: 'session   required    /lib/security/pam_limits.so'
    state: present
    insertafter: EOF
  when: 'ansible_architecture != "x86_64"'