---
- name: Disabling SELINUX
  selinux:
    state: disabled
  failed_when: false


- name: Disabling SELINUX (Enforcing)
  command: setenforce Enforcing
  failed_when: false


- name: Removing SELINUX Policy
  yum:
    name: 'selinux-policy'
    state: absent
  failed_when: false
