---
- name: Retrieving IP's 3rd Octet
  command: echo "{{ ansible_host.split('.')[-2] }}"
  register: last_octet0

- name: Retrieving IP's 4th Octet
  command: echo "{{ ansible_host.split('.')[-1] }}"
  register: last_octet
    
- name: Changing Hostname
  hostname:
    name: china-ssrvpn-{{ last_octet0.stdout }}-{{ last_octet.stdout }}

