---
- name: Removing old repo
  shell: 'rm -f /etc/yum.repos.d/*'
  ignore_errors: yes


- name: Installing centos5
  block:
  - name: Installing centos5 rpm(x86_64)
    block:
      - name: Coping epel-release-5-4 (x86_64)
        copy:
          src: epel-release-5-4-x86_64.noarch.rpm
          dest: /root/
      - name: Installing epel-release-5-4 (x86_64)
        command: rpm -Uvh /root/epel-release-5-4-x86_64.noarch.rpm
        failed_when: false
    when: 'ansible_architecture == "x86_64"'
  - name: Installing centos5 rpm(i386)
    block:
      - name: Coping epel-release-5-4 (i386)
        copy:
          src: epel-release-5-4-i386.noarch.rpm
          dest: /root/
      - name: Installing epel-release-5-4 (i386)
        command: rpm -Uvh /root/epel-release-5-4-i386.noarch.rpm
        failed_when: false
    when: 'ansible_architecture != "x86_64"'
  when: 'ansible_distribution_major_version == "5"'



- name: Installing centos6
  block:
  - name: Installing centos6 rpm(x86_64)
    block:
      - name: Coping epel-release-6-8 (x86_64)
        copy:
          src: epel-release-6-8-x86_64.noarch.rpm
          dest: /root/
      - name: Installing epel-release-6-8 (x86_64)
        command: rpm -Uvh /root/epel-release-6-8-x86_64.noarch.rpm
        failed_when: false
    when: 'ansible_architecture == "x86_64"'
  - name: Installing centos6 rpm(i386)
    block:
      - name: Coping epel-release-6-8 (i386)
        copy:
          src: epel-release-6-8-i386.noarch.rpm
          dest: /root/
      - name: Installing epel-release-6-8 (x86_64)
        command: rpm -Uvh /root/epel-release-6-8-i386.noarch.rpm
        failed_when: false
    when: 'ansible_architecture != "x86_64"'
  when: 'ansible_distribution_major_version == "6"'




- name: Installing centos7
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: '{{ item.own_grp }}'
    group: '{{ item.own_grp }}'
    mode: '{{ item.mod }}'
  with_items:
    - { src: 'epel.repo.j2', dest: '/etc/yum.repos.d/epel.repo', own_grp: 'root', mod: '0644' }
    - { src: 'CentOS-Base.repo.j2', dest: '/etc/yum.repos.d/CentOS-Base.repo', own_grp: 'root', mod: '0644' }
  when: 'ansible_distribution_major_version == "7"'




- name: Configuring /etc/yum.repos.d/epel.repo
  replace:
    path: "/etc/yum.repos.d/epel.repo"
    regexp: "mirrorlist=https"
    replace: "mirrorlist=http"
  failed_when: false


