---
- include: hostname.yml
- include: install_first.yml
- include: disabling_selinux.yml
- include: installing_centos_rpm.yml
- include: installing_packages.yml
- include: configuring_ommgr_user.yml
- include: filesystem_check.yml
- include: configuring_pam_login.yml
- include: configuring_limits.yml
- include: template_process.yml
- include: zabbix_release6.yml
  when: (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "6")
- include: zabbix_release7.yml
  when: (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "7") 
- include: zabbix_restart.yml
- include: enabling_services.yml
- include: restarting_ssh_and_rsyslog.yml
- include: changing_root_password.yml
