---
- name: Create ssh dir to root
  file:
    path: '/root/.ssh'
    state: directory
    owner: root
    group: root
    mode: 0700

- name: Configuring files
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: '{{ item.own_grp }}'
    group: '{{ item.own_grp }}'
    mode: '{{ item.mod }}'
  vars:
    vpn_ssh_port: '{{ ssr_port }}'
    vpn_ssh_user: '{{ ssr_user }}'
  with_items:
    - { src: 'inittab.j2', dest: '/etc/inittab', own_grp: 'root', mod: '0644' }
    - { src: 'crontab.j2', dest: '/etc/crontab', own_grp: 'root', mod: '0644' }
    - { src: 'crontab.j2', dest: '/var/spool/cron/root', own_grp: 'root', mod: '0600' }
    - { src: 'sshd_config.j2', dest: '/etc/ssh/sshd_config', own_grp: 'root', mod: '0644' }
    - { src: 'hosts.j2', dest: '/etc/hosts', own_grp: 'root', mod: '0644' }
    - { src: 'network.j2', dest: '/etc/sysconfig/network', own_grp: 'root', mod: '0644' }
    - { src: 'bashrc.j2', dest: '/root/.bashrc', own_grp: 'root', mod: '0644' }
    - { src: 'resolv.conf.j2', dest: '/etc/resolv.conf', own_grp: 'root', mod: '0644' }
    - { src: 'rc.local.j2', dest: '/etc/rc.d/rc.local', own_grp: 'root', mod: '0755' }
    - { src: 'bashrc.j2', dest: '/home/{{ ssr_user }}/.bashrc', own_grp: '{{ ssr_user }}', mod: '0644' }
    - { src: 'authorized_keys.j2', dest: '/home/{{ ssr_user }}/.ssh/authorized_keys', own_grp: '{{ ssr_user }}', mod: '0600' }
    - { src: 'authorized_keys_root.j2', dest: '/root/.ssh/authorized_keys', own_grp: 'root', mod: '0600' }
    - { src: 'su.j2', dest: '/etc/pam.d/su', own_grp: 'root', mod: '0644' }

