---

- name: Check systemctl
  stat:
    path: '/usr/bin/systemctl'
  register: systemctl_loc


- name: Restarting Zabbix-Agent Service
  systemd:
    name: '{{ item }}'
    state: restarted
    enabled: yes
  with_items:
    - zabbix-agent
  when: 'systemctl_loc.stat.path is defined'



- name: Restarting Zabbix-Agent Service (2)
  command: '/etc/init.d/{{ item }} restart'
  with_items:
    - zabbix-agent
  when: 'systemctl_loc.stat.path is not defined'

