# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-02 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NGINX_CONFIG_LOCATION',
            fields=[
                ('host_group', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Ansible Hostgroup')),
                ('test_host', models.GenericIPAddressField(blank=True, null=True, verbose_name='Test Host')),
                ('config_src', models.CharField(max_length=100, verbose_name='Config Source')),
            ],
            options={
                'verbose_name': 'Internal Nginx Hosts',
                'verbose_name_plural': 'Internal Nginx Hosts',
            },
        ),
    ]
