# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-04 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwdcontrol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nginx_config_location',
            name='test_host',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Test Host'),
        ),
    ]
