# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-10 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fwdcontrol', '0002_auto_20180104_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nginx_config_location',
            name='test_host',
        ),
        migrations.AlterField(
            model_name='nginx_config_location',
            name='host_group',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Ansible Hostgroup'),
        ),
    ]
