# Generated by Django 2.2 on 2019-11-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SSRconfighistoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USERNAME', models.CharField(max_length=50, null=True)),
                ('IP', models.TextField(null=True)),
                ('PORT', models.IntegerField(null=True)),
                ('STATUS', models.CharField(max_length=10, null=True)),
                ('LOGS', models.TextField(null=True)),
                ('DATE', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SSRconfigsummaryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.CharField(max_length=16, null=True)),
                ('PORT', models.IntegerField(null=True)),
                ('IDC', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SSRinitdataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.CharField(max_length=16, null=True)),
                ('PORT', models.IntegerField(null=True)),
                ('STATUS', models.CharField(max_length=10, null=True)),
                ('SSR_LINK', models.TextField(null=True)),
                ('SSR_CODE', models.TextField(null=True)),
                ('SS_LINK', models.TextField(null=True)),
                ('SS_CODE', models.TextField(null=True)),
                ('IDC', models.CharField(max_length=20, null=True)),
                ('LAST_CHECK', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SSRinithistoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USERNAME', models.CharField(max_length=50, null=True)),
                ('IP', models.CharField(max_length=16, null=True)),
                ('STATUS', models.CharField(max_length=10, null=True)),
                ('LOGS', models.TextField(null=True)),
                ('IDC', models.CharField(max_length=20, null=True)),
                ('CREATED', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SSRinitModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.CharField(max_length=16, null=True)),
                ('PORT', models.IntegerField(null=True)),
                ('USER', models.CharField(max_length=15, null=True)),
                ('PASSWORD', models.CharField(max_length=50, null=True)),
                ('IDC', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SSRmasterconfighistoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USERNAME', models.CharField(max_length=50, null=True)),
                ('IP', models.TextField(null=True)),
                ('PORT', models.IntegerField(null=True)),
                ('FILE', models.CharField(max_length=50, null=True)),
                ('CHANGED_ADDED', models.TextField(null=True)),
                ('PREVIOUS', models.TextField(null=True)),
                ('DATE', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
