# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-31 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSRCHECKER', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSRhomehistoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USERNAME', models.CharField(max_length=50, null=True)),
                ('IP', models.TextField(null=True)),
                ('STATUS', models.CharField(max_length=50, null=True)),
                ('IDC', models.CharField(max_length=50, null=True)),
                ('LOGS', models.TextField(null=True)),
                ('ACTION', models.CharField(max_length=50, null=True)),
                ('DATE', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
