# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-06 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSRCHECKER', '0002_ssrhomehistorymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssrconfighistorymodel',
            name='STATUS',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='ssrinitdatamodel',
            name='STATUS',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='ssrinithistorymodel',
            name='STATUS',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
