# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-04-26 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSRCHECKER', '0003_auto_20200207_0337'),
    ]

    operations = [
        migrations.CreateModel(
            name='V2rayconfighistoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.TextField(null=True)),
                ('V2RAY_USERNAME', models.TextField(null=True)),
                ('V2RAY_STATUS', models.TextField(null=True)),
                ('V2RAY_LOGS', models.TextField(null=True)),
                ('V2RAY_DATE', models.TextField(null=True)),
                ('V2RAY_PORT', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='V2rayconfigsummaryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.CharField(max_length=16, null=True)),
                ('IDC', models.CharField(max_length=20, null=True)),
                ('V2RAY_PORT', models.IntegerField(null=True)),
                ('V2RAY_PATH', models.TextField(null=True)),
                ('V2RAY_DOMAIN', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ssrhomehistorymodel',
            name='LOGS',
        ),
        migrations.AddField(
            model_name='ssrinitdatamodel',
            name='V2RAY_DATE',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ssrinitdatamodel',
            name='V2RAY_DOMAIN',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ssrinitdatamodel',
            name='V2RAY_PATH',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ssrinitdatamodel',
            name='V2RAY_PORT',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ssrinitdatamodel',
            name='V2RAY_STATUS',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ssrinitdatamodel',
            name='V2RAY_URL',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ssrinitmodel',
            name='V2RAY_DOMAIN',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ssrinitmodel',
            name='V2RAY_PATH',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ssrinitmodel',
            name='V2RAY_PORT',
            field=models.IntegerField(null=True),
        ),
    ]
