# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-16 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domainexpiry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domainexpiry',
            name='renewal',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='domainexpiry',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
