# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-18 06:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domainexpiry', '0003_domainrenewal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='domainRenewal',
        ),
    ]
