# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-24 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domainexpiry', '0004_delete_domainrenewal'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainexpiry',
            name='audit',
            field=models.IntegerField(default=0),
        ),
    ]
