# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-24 07:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domainexpiry', '0005_domainexpiry_audit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domainexpiry',
            name='audit',
        ),
    ]
