# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-02 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domainexpiry', '0006_remove_domainexpiry_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainexpiry',
            name='tag',
            field=models.CharField(default='', max_length=20),
        ),
    ]
