---

- name: Check if 233blog_v2ray_config.json file already exist

  stat:

    path: '{{ v2ray_client_config }}'

  register: v2ray_config



- name: Check if user-config.json file already exist

  stat:

    path: '{{ config_user_file }}'

  register: ssr_config







- name: Check if shadowsocksr directory already exist

  stat:

    path: '{{ ssr_folder }}'

  register: ssr_dir


