---

- name: Configuring v2ray systemctl

  replace:

    path: /lib/systemd/system/v2ray.service

    regexp: 'on-failure'

    replace: 'always'

#  ignore_errors: yes





- name: Enabling v2ray systemctl

  systemd:

    name: v2ray

    enabled: yes

    state: restarted

#  ignore_errors: yes





- name: Enabling v2ray service

  service:

    name: v2ray

    enabled: yes

    state: restarted

  ignore_errors: yes
