---

- name: Get UUID

  slurp:

    path: /proc/sys/kernel/random/uuid

  register: uuid_data









- name: IP last octet

  command: echo "{{ ansible_host.split('.')[-1] }}"

  register: last_octet
