---

- include: check_requirements.yml

- include: configuring_iptables.yml

- block:

  - include: getting_v2ray_files.yml

  - include: getting_variables.yml

  - include: copy_and_permission.yml

  - include: configuring_v2ray.yml

  - include: configuring_services.yml

  when: 'v2ray_config.stat.path is not defined  and ssr_config.stat.path is defined and ssr_dir.stat.path is defined'


