# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-14 01:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CONTACT',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Contact Name')),
                ('number', models.BigIntegerField(verbose_name='Contact Number')),
            ],
            options={
                'verbose_name': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='GROUP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Group Name')),
            ],
            options={
                'verbose_name': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='MEMBERSHIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='smsalerts.CONTACT', verbose_name='Contact ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='smsalerts.CONTACT', verbose_name='Group ID')),
            ],
            options={
                'verbose_name': 'Memberships',
            },
        ),
        migrations.CreateModel(
            name='MESSAGE_QUEUE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=128, verbose_name='Message')),
                ('last_sent', models.DateTimeField(verbose_name='Last Sent')),
                ('freq_minutes', models.IntegerField(verbose_name='Frequency (Mins)')),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smsalerts.CONTACT', verbose_name='Contact ID')),
            ],
            options={
                'verbose_name': 'Message Queue',
            },
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together=set([('contact', 'group')]),
        ),
    ]
