# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-14 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsalerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Group'},
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'verbose_name': 'Membership'},
        ),
        migrations.AddField(
            model_name='message_queue',
            name='flags',
            field=models.PositiveIntegerField(default=0, verbose_name='Bit Flags'),
        ),
    ]
