# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-14 02:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smsalerts', '0002_auto_20181114_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message_queue',
            old_name='contact_id',
            new_name='contact',
        ),
    ]
