# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-14 02:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smsalerts', '0003_auto_20181114_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message_queue',
            name='contact',
        ),
        migrations.AddField(
            model_name='message_queue',
            name='group',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='smsalerts.GROUP', verbose_name='Group ID'),
            preserve_default=False,
        ),
    ]
