############
version: '2'
services:
 argus-task-scheduler:
  #build: .
  image: omdockerhub.neweb.me:5000/argus-web
  container_name: argus-task-scheduler
  volumes:
    - /etc/localtime:/etc/localtime:ro
    #- /opt/logs/argus/:/app/argus/logs
  hostname: argus-task-scheduler
  mem_limit: 2g
  memswap_limit: 2g
  command: bash /app/argus/exec/sync-start-task-scheduler.sh
  stdin_open: true
  tty: true
  user: root
  dns:
    - 10.168.11.100
    - 10.167.11.100
  user: root
  network_mode: "bridge"
