############
version: '2'
services:
 argus-web:
  #build: .
  image: omdockerhub.neweb.me:5000/argus-web
  container_name: argus-web
  ports:
    - "8000:8005"
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /app/argus/mount/argus-celery-app-eye/screenshots/:/app/argus/static/screenshots/:ro
  hostname: argus-web
  mem_limit: 2g
  memswap_limit: 2g
  command: /bin/bash
  stdin_open: true
  tty: true
  user: root
  dns:
    - 10.168.11.100
    - 10.167.11.100
  user: root
  network_mode: "bridge"