# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-03-28 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GROUPS',
            fields=[
                ('group', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='Hostname')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Group',
            },
        ),
        migrations.CreateModel(
            name='HOSTS',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=64, verbose_name='Hostname')),
                ('host_ip', models.GenericIPAddressField(unique=True, verbose_name='Host IP')),
            ],
            options={
                'verbose_name': 'Host',
                'verbose_name_plural': 'Host',
            },
        ),
        migrations.AddField(
            model_name='groups',
            name='host_id',
            field=models.ManyToManyField(to='inventory.HOSTS', verbose_name='Host'),
        ),
    ]
