# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-03-28 08:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groups',
            old_name='host_id',
            new_name='hosts',
        ),
    ]
