# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-04-01 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20190328_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='group',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='Group'),
        ),
    ]
