# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-04-02 05:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20190401_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLOUD_HOST',
            fields=[
                ('host', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inventory.HOSTS', verbose_name='ID')),
                ('cpu_core_count', models.IntegerField(blank=True, null=True, verbose_name='CPU Core Count')),
                ('memory', models.FloatField(blank=True, null=True, verbose_name='Memory')),
                ('storage', models.FloatField(blank=True, null=True, verbose_name='Storage')),
                ('service_provider', models.CharField(blank=True, max_length=32, null=True, verbose_name='Service Provider')),
                ('last_renewed', models.DateField(blank=True, null=True, verbose_name='Last Renewed')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
            ],
            options={
                'verbose_name': 'Cloud Servers',
                'verbose_name_plural': 'Cloud Servers',
            },
        ),
        migrations.AddField(
            model_name='hosts',
            name='hosttype',
            field=models.CharField(default='CLOUD_HOST', max_length=64, verbose_name='Host Type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hosts',
            name='hostname',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Hostname'),
        ),
    ]
