# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-04-08 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20190402_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloud_host',
            name='remarks',
        ),
        migrations.AddField(
            model_name='hosts',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks'),
        ),
    ]
