# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-04-10 06:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_cloud_host_creation_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloud_host',
            old_name='cpu_core_count',
            new_name='cpu_count',
        ),
    ]
