# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-07-01 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20190410_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='COUNTRY_CODES',
            fields=[
                ('country_code', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Country Code')),
                ('location', models.CharField(max_length=50, verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Country Codes',
                'verbose_name_plural': 'Country Codes',
            },
        ),
    ]
