# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-07-01 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_country_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country_codes',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Country'),
        ),
    ]
