# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-07-02 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20190701_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosts',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, to='inventory.GROUPS', verbose_name='Groups'),
        ),
    ]
