# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-02 05:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_auto_20180924_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACCOUNTS',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Username')),
                ('token', models.CharField(max_length=100, verbose_name='Token/Password')),
                ('provider', models.CharField(max_length=100, verbose_name='Provider')),
                ('tag', models.CharField(blank=True, max_length=50, null=True, verbose_name='tag')),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.BUSINESS_UNIT', verbose_name='Business Unit')),
            ],
            options={
                'verbose_name': 'Accounts',
                'verbose_name_plural': 'Accounts',
            },
        ),
    ]
