# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-02 05:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0002_auto_20190102_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='DOMAIN',
            fields=[
                ('domain', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Domain Name')),
                ('expiry', models.DateField(blank=True, null=True, verbose_name='Expire Date')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domains.ACCOUNT', verbose_name='Registrar Account')),
            ],
            options={
                'verbose_name': 'Domains',
                'verbose_name_plural': 'Domains',
            },
        ),
    ]
