---
  - name: Copying sshd_config         #Copying sshd_config file to server
    template:
      src: sshd_config.j2
      dest: /etc/ssh/sshd_config





  - name: Restarting ssh service      #restarting ssh service
    systemd:
     name: sshd.service
     state: restarted