---
  - name: Getting-IP
    shell: "curl -s ipinfo.io > /tmp/ip-info"
  - name: Check-country
    shell: cat /tmp/ip-info|jq '.country'|awk '{print tolower($0)}' | sed -e 's/^"//' -e 's/"$//'
    register: cntry