  - name: Yum clean and makecache                    #Yum clean and makecache
    shell: yum clean all && yum makecache
  - name: Installing packages2                       #installing packages
    yum:
     name:
     - "{{ item }}"
     state: present
    with_items:
     - epel-release
     - vim-enhanced
     - net-tools
     - lsof
     - wget
     - cronie
     - ntp
     - lrzsz
     - gcc
     - gcc-c++
     - make
     - cmake
     - libxml2-devel
     - openssl-devel
     - curl
     - curl-devel
     - unzip
     - sudo
     - libaio-devel
     - ncurses-devel
     - autoconf
     - automake
     - zlib-devel
     - python-devel
     - iptables-services
     - policycoreutils
     - openssh-clients
     - iproute
     - telnet
     - xinetd
     - git
     - psmisc
  - name: Removing package                          #removing packages
    yum:
     name:
     - "{{ item }}"
     state: absent
    with_items:
     - lyx-fonts
     - selinux-policy*
     - firewalld
     - iw*
     - NetworkManager*
     - wpa_supplicant
     - newt
     - dnsmasq
