---
- include: pre_tasks.yml                                  #Configuring /etc/resolv.conf to 8.8.8.8 and 8.8.4.4
- include: requirements_check.yml                         #Checking if the server is centos7, if not initialization will stop
- include: hostname.yml                                   #Changing hostname. Based on on vars directory
- include: installing_and_removing_packages.yml           #Installing and removing packages
- include: setting_up_ommgr_user.yml                      #Setting up ommgr user including authorize keys and others
- include: setting_up_root.yml                            #Setting up root user including authorize keys and .ssh directory
- include: setting_up_system.yml                          #Setting up rsyslog.conf, iptables and others
- include: configuring_ssh.yml                            #Configuring ssh file to port 28032
- include: setting_up_system2.yml                         #Stop unnecessary service and configure other files like /etc/sysctl.conf
- include: setting_up_cron_and_timezone_hk.yml            #Setting up crontab and timezone
#- include: installing_zabbix.yml                            #installing zabbix-agent and configuring it
- include: instalation_completed.yml                      #Source .bashrc and /etc/profile. And changing root password based on vars directory


