---
  - name: Creating root directory                                                   #Creating root directory
    file:
      path: /root/.ssh
      owner: root
      group: root
      state: directory
      mode: 0700
  - name: Downloading root authorized_keys                                          #Downloading root authorized_keys
    get_url:
      url: http://office.pc-setting.info/cyrus/ugatnasusi
      url_username: '{{ username }}'
      url_password: '{{ pc_settings_password }}'
      dest: /root/.ssh/authorized_keys
      mode: 0600