# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-19 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HOSTGROUP_CONFIG',
            fields=[
                ('host_group', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Ansible Hostgroup')),
                ('access_level', models.CharField(choices=[(b'SIMPLE', b'SIMPLE'), (b'SPECIFIC', b'SPECIFIC'), (b'OPEN', b'OPEN')], max_length=30, verbose_name='Access Level')),
            ],
            options={
                'verbose_name': 'Hostgroup Configuration',
                'verbose_name_plural': 'Hostgroup Configuration',
            },
        ),
    ]
