# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-19 03:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('esync', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SPECIFIC_HOSTGROUP_ACCESS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esync.HOSTGROUP_CONFIG', verbose_name='Ansible Hostgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Hostgroup Permissions',
                'verbose_name_plural': 'Hostgroup Permissions',
            },
        ),
        migrations.AlterUniqueTogether(
            name='specific_hostgroup_access',
            unique_together=set([('host_group', 'user')]),
        ),
    ]
