# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-20 06:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180905_0936'),
        ('esync', '0002_auto_20180919_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostgroup_config',
            name='business_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.BUSINESS_UNIT', verbose_name='Business Unit'),
        ),
    ]
