# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-06-28 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esync', '0003_hostgroup_config_business_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='TEMPLATES',
            fields=[
                ('templateName', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Template Name')),
                ('applicationType', models.CharField(max_length=20, verbose_name='Application Type')),
                ('template', models.TextField(verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Templates',
                'verbose_name_plural': 'Templates',
            },
        ),
    ]
