# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-07-01 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esync', '0004_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='INITIALIZATION_TYPES',
            fields=[
                ('initialization_type', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Initialization Type')),
                ('initialization_name', models.CharField(max_length=20, verbose_name='Initialization Name')),
            ],
            options={
                'verbose_name': 'Initialization Types',
                'verbose_name_plural': 'Initialization Types',
            },
        ),
        migrations.AlterUniqueTogether(
            name='initialization_types',
            unique_together=set([('initialization_type', 'initialization_name')]),
        ),
    ]
