# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-07-01 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esync', '0005_auto_20190701_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='SERVICE_PROVIDERS',
            fields=[
                ('service_provider', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Service Prov')),
                ('service_provider_prefix', models.CharField(blank=True, max_length=3, null=True, verbose_name='Initialization Name')),
            ],
            options={
                'verbose_name': 'Service Providers',
                'verbose_name_plural': 'Service Providers',
            },
        ),
    ]
