# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-07-01 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esync', '0006_service_providers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_providers',
            name='service_provider',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Service Provider'),
        ),
        migrations.AlterField(
            model_name='service_providers',
            name='service_provider_prefix',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Prefix'),
        ),
    ]
