# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-07-02 06:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20190702_1352'),
        ('esync', '0007_auto_20190701_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='INITIALIZED_SERVERS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initialization_status', models.CharField(default='IN_PROGRESS', max_length=20, verbose_name='Status')),
                ('hosts_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.HOSTS', verbose_name='Host')),
            ],
            options={
                'verbose_name': 'Initialized Servers',
                'verbose_name_plural': 'Initialized Servers',
            },
        ),
    ]
