# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-07-02 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esync', '0008_initialized_servers'),
    ]

    operations = [
        migrations.AddField(
            model_name='initialized_servers',
            name='logfile',
            field=models.CharField(default='', max_length=100, verbose_name='Log File'),
            preserve_default=False,
        ),
    ]
