# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-07-03 03:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_hosts_enabled'),
        ('esync', '0012_auto_20190702_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='initialized_servers',
            name='country_code',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='inventory.COUNTRY_CODES', verbose_name='Country Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='initialized_servers',
            name='initialization_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='esync.INITIALIZATION_TYPES', verbose_name='Initialization Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='initialized_servers',
            name='service_provider',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='esync.SERVICE_PROVIDERS', verbose_name='Service Provider'),
            preserve_default=False,
        ),
    ]
