# Generated by Django 2.2.6 on 2019-10-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSLDOMAINS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssldomain',
            name='date_now',
            field=models.TextField(default=''),
        ),
    ]
