# Generated by Django 2.2.6 on 2019-10-21 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SSLDOMAINS', '0002_auto_20191019_0548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ssldomain',
            name='project',
        ),
    ]
