# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-11-04 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SSLDOMAINS', '0004_ssldomain_daysleft'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testdb',
        ),
    ]
