# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-05 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSLDOMAINS', '0006_logstable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logstable',
            name='logs_field',
            field=models.TextField(default=b'', max_length=100),
        ),
        migrations.AlterField(
            model_name='ssldomain',
            name='date_now',
            field=models.TextField(default=b'', max_length=50),
        ),
        migrations.AlterField(
            model_name='ssldomain',
            name='daysleft',
            field=models.TextField(default=b'', max_length=50),
        ),
        migrations.AlterField(
            model_name='ssldomain',
            name='expiration',
            field=models.TextField(default=b'', max_length=50),
        ),
        migrations.AlterField(
            model_name='ssldomain',
            name='status',
            field=models.IntegerField(default=0, max_length=50),
        ),
    ]
