# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-05 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSLDOMAINS', '0007_auto_20200205_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='sslDomain2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(default=b'', max_length=20)),
                ('expiration', models.TextField(default=b'', max_length=50)),
                ('date_now', models.TextField(default=b'', max_length=50)),
                ('status', models.IntegerField(default=0, max_length=50)),
                ('daysleft', models.TextField(default=b'', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='logstable',
            name='test',
            field=models.TextField(default=b'', max_length=100),
        ),
    ]
