# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2021-04-28 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSLDOMAINS', '0008_auto_20200206_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssldomain2',
            name='business_unit',
            field=models.TextField(default=b'', max_length=50),
        ),
        migrations.AddField(
            model_name='ssldomain2',
            name='port443',
            field=models.TextField(default=b'', max_length=50),
        ),
        migrations.AddField(
            model_name='ssldomain2',
            name='port80',
            field=models.TextField(default=b'', max_length=50),
        ),
        migrations.AddField(
            model_name='ssldomain2',
            name='skip',
            field=models.TextField(default=b'', max_length=50),
        ),
    ]
