# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2021-04-28 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSLDOMAINS', '0009_auto_20210428_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssldomain2',
            name='port443',
            field=models.TextField(default=b'open', max_length=50),
        ),
        migrations.AlterField(
            model_name='ssldomain2',
            name='port80',
            field=models.TextField(default=b'open', max_length=50),
        ),
        migrations.AlterField(
            model_name='ssldomain2',
            name='skip',
            field=models.TextField(default=b'no', max_length=50),
        ),
    ]
