# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2021-10-17 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSLDOMAINS', '0010_auto_20210428_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssldomain2',
            name='domain',
            field=models.CharField(default=b'', max_length=80),
        ),
    ]
