# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2021-10-20 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSLDOMAINS', '0011_auto_20211017_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssldomain',
            name='domain',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AlterField(
            model_name='ssldomain2',
            name='domain',
            field=models.CharField(default=b'', max_length=100),
        ),
    ]
