---

- name: Removing old nginx config

  shell: rm -rf /etc/nginx/conf.d/*



- name: Removing old nginx config2

  file:

   path: "{{ item }}"

   state: absent

  with_items:

    - "/etc/nginx/conf.d/default.conf"

    - "/usr/share/nginx/html"



- name: Create ssl directory

  file:

    path:  "{{ item }}"

    state: directory

  with_items:

    - "/etc/nginx/conf.d/ssl/"

    - "/etc/nginx/conf.d/ssl/{{ v2ray_domain }}"

    - "/root/extract/"





- name: Adding new nginx config

  template:

    dest: '{{ item.dest }}'

    src: '{{ item.src }}'

  vars:

    v2ray_idcip: "{{ v2ray_idc }}{{ last_octet.stdout }}"

  with_items:

    - dest: "/etc/nginx/conf.d/{{ v2ray_idcip }}.{{ v2ray_domain }}.conf"

      src: "nginx.conf.j2"

    - dest: "/etc/nginx/conf.d/ssl/{{ v2ray_domain }}/fullchain.pem"

      src: "{{ v2ray_domain }}_fullchain.pem.j2"

    - dest: "/etc/nginx/conf.d/ssl/{{ v2ray_domain }}/privkey.pem"

      src: "{{ v2ray_domain }}_privkey.pem.j2"
