---

- name: V2ray data

  slurp:

    path: /etc/v2ray/v2ray_url.json

  register: v2ray_json







- name: V2ray information

  debug:

    msg:

      - "V2ray URL          :     vmess://{{ (v2ray_json.content) }}"

      - "V2ray Domain       :     {{ hostvars[inventory_hostname]['inventory_hostname'] }} ===> https://{{ v2ray_idc }}{{ last_octet.stdout }}.{{ v2ray_domain }}"
