# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-01 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LE_LOGGING',
            fields=[
                ('logging_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=50, verbose_name='Domain')),
                ('activity', models.TextField(verbose_name='Activity')),
                ('activity_type', models.CharField(choices=[(b'FAIL', b'FAIL'), (b'SUCCESS', b'SUCCESS')], max_length=30, verbose_name='Activity Type')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
            ],
            options={
                'verbose_name': 'LE Manager Activity Logs',
                'verbose_name_plural': 'LE Manager Activity Logs',
            },
        ),
        migrations.CreateModel(
            name='LE_PROC_ID',
            fields=[
                ('logging_id', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='le_logging',
            name='process_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LEManager.LE_PROC_ID'),
        ),
    ]
