# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-01 11:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LEManager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='le_proc_id',
            old_name='logging_id',
            new_name='process_id',
        ),
    ]
