# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-01 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LEManager', '0002_auto_20180301_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='le_proc_id',
            name='process_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
