# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-01 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LEManager', '0003_auto_20180301_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='le_proc_id',
            name='process_id',
            field=models.CharField(max_length=60, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
