# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-01 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LEManager', '0004_auto_20180301_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='le_proc_id',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Timestamp'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='le_logging',
            name='activity_type',
            field=models.CharField(choices=[(b'CREATE', b'CREATE'), (b'MANUAL RENEWAL', b'MANUAL RENEWAl')], max_length=30, verbose_name='Activity Type'),
        ),
    ]
