# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-08 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LEManager', '0005_auto_20180301_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='le_logging',
            name='activity_type',
            field=models.CharField(choices=[(b'CREATE', b'CREATE'), (b'RENEW', b'RENEW'), (b'UPDATE', b'UPDATE')], max_length=30, verbose_name='Activity Type'),
        ),
    ]
