# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-11 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LEManager', '0007_le_logging_activity_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='le_logging',
            name='activity_status',
        ),
        migrations.AddField(
            model_name='le_proc_id',
            name='activity_status',
            field=models.CharField(choices=[(b'PENDING', b'PENDING'), (b'FAILED', b'FAILED'), (b'SUCCESS', b'SUCCESS')], default='SUCCESS', max_length=30, verbose_name='Activity Status'),
            preserve_default=False,
        ),
    ]
