# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-12 07:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LEManager', '0008_auto_20180311_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='le_proc_id',
            options={'verbose_name': 'LE Manager Process IDs', 'verbose_name_plural': 'LE Manager Process IDs'},
        ),
    ]
