---
- name: Downloading shadowsocks
  copy:
    src: shadowsocksr.zip
    dest: /usr/local/



- name: Extracting shadowsocks
  unarchive:
    remote_src: yes
    src: /usr/local/shadowsocksr.zip
    dest: /usr/local/



- name: Removing shadowsocksr.zip
  file:
    path: /usr/local/shadowsocksr.zip
    state: absent



- name: Make directory shadowsocks at /etc
  file:
    path: /etc/shadowsocksr
    state: directory