---
- name: Installing jq x86_64
  copy:
    remote_src: yes
    src: '{{ ssr_folder }}/jq-linux64'
    dest: '{{ jq_file }}'
    mode: '+x'
  when: 'ansible_architecture == "x86_64"'



- name: Installing jq i386
  copy:
    remote_src: yes
    src: '{{ ssr_folder }}/jq-linux32'
    dest: '{{ jq_file }}'
    mode: '+x'
  when: 'ansible_architecture != "x86_64"'