---
- include: ssr_check.yml
- block:
  - include: installation_dependency.yml
  - include: download_ssr.yml
  - include: ssr_service.yml
  - include: jq_install.yml
  when: 'user_config.stat.path is not defined and ssr_dir.stat.path is not defined'


