---
- name: Downloading ssr service Redhat family
  template:
    src: ssr_redhat.j2
    dest: /etc/init.d/ssr
    mode: "+x"
  when: 'ansible_os_family == "RedHat"'



- name: Downloading ssr service Debian family
  template:
    src: ssr_redhat.j2
    dest: /etc/init.d/ssr
    mode: "+x"
  when: 'ansible_os_family != "RedHat"'



- name: Enabling ssr service
  service:
    name: ssr
    enabled: yes