# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-24 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdndomain',
            name='audit',
            field=models.TextField(default='No', max_length=50),
        ),
    ]
