# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-01 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdn', '0002_auto_20201124_0753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cdndomain',
            name='date_now',
        ),
        migrations.RemoveField(
            model_name='cdndomain',
            name='daysleft',
        ),
        migrations.RemoveField(
            model_name='cdndomain',
            name='expiration',
        ),
        migrations.AddField(
            model_name='cdndomain',
            name='tag',
            field=models.IntegerField(default=1),
        ),
    ]
