# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-01 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdn', '0003_auto_20201201_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdndomain',
            name='tag',
            field=models.CharField(default='B2B', max_length=20),
        ),
    ]
